import json
import boto3
import urllib.request
import xml.etree.ElementTree as ET

def lambda_handler(event, context):
    # Fetch all global GDACS events
    url = "https://gdacs.org/xml/rss.xml"
    
    print(f"URL: {url}")
    
    try:
        # Query GDACS API
        with urllib.request.urlopen(url) as f:
            data = ET.fromstring(f.read().decode())
        print("API Status: 200")
    except Exception as e:
        print(f"Fetch error: {type(e).__name__}: {e}")
        return {"statusCode": 500, "body": f"Failed: {e}"}
    
    # Process disaster alerts
    alerts = []
    for item in data.findall(".//item"):
        title = item.find("title").text
        pub_date = item.find("pubDate").text[:16]  # Extract date (e.g., "Tue, 28 Sep 2025")
        alerts.append(f"- {title} (Updated: {pub_date})")
    
    if alerts:
        ses = boto3.client("ses", region_name="us-east-1")
        try:
            # Send email
            ses.send_email(
                Source="abhinavranascorpio@gmail.com",
                Destination={"ToAddresses": ["abhinavranascorpio@gmail.com"]}, 
                Message={
                    "Subject": {"Data": "SAGE: GDACS Disaster Alerts"},
                    "Body": {"Text": {"Data": "GDACS Disaster Alerts\n\n" + "\n".join(alerts) + "\n\nGenerated by SAGE PROJECT"}}
                }
            )
            print(f"Sent {len(alerts)} alerts")
        except Exception as e:
            print(f"SES error: {e}")
            return {"statusCode": 500, "body": f"SES failed: {e}"}
    
    return {"statusCode": 200, "body": f"{len(alerts)} alerts"}
